#这个是记录所有控件id的地方
#只记录id，xpth地址在别的地方

APPIUM输入法='io.appium.android.ime/.UnicodeIME'
安卓6请求权限的弹窗='com.android.packageinstaller:id/permission_allow_button'
####################
教练pad='com.kk.coachpad'
登录页面的Activity= '.ui.activity.LoginActivity'
登录_密码='login_input_password'
登录_账号='login_input_user_name'
登录按钮='login_btn'
登录页面_快快身体评测='com.kk.coachpad:id/body_measure_btn'
体验版体测='com.kk.coachpad:id/test_measure'
专业版体测='com.kk.coachpad:id/major_measure'
私教版体测='com.kk.coachpad:id/pt_measure'
未上传体测='com.kk.coachpad:id/not_upload_measure'
专业版体测_手动输入='com.kk.coachpad:id/tv_hand_code'
专业版体测_输入用户id='com.kk.coachpad:id/et_hurt_position'
课程标题='com.kk.coachpad:id/course_title'

连接臂带='tv_bind'
绑定臂带='tv_bind'
课程剩余时间='com.kk.coachpad:id/tv_unit_time_remain'
单元小节图片='com.kk.coachpad:id/unit_image'
报告页标题='com.kk.coachpad:id/title_name'
课程结束提醒='com.kk.coachpad:id/tv_count_down'
弹窗_取消='com.kk.coachpad:id/tv_finish'
弹窗_确认='com.kk.coachpad:id/btn_confirm'
课程列表_标题='com.kk.coachpad:id/title'
课程列表_门店='com.kk.coachpad:id/tv_kk_store'
课程列表_体测='com.kk.coachpad:id/body_ms'
课程列表_设置='com.kk.coachpad:id/setting'
课程列表_当前门店='com.kk.coachpad:id/tv_store_name'
门店列表='com.kk.coachpad:id/tv_gym'
###设置页面_
设置页面_教练名='com.kk.coachpad:id/tv_user_name'
设置页面_性别='com.kk.coachpad:id/tv_user_sex'
设置页面_工作年限='com.kk.coachpad:id/tv_user_year'
设置页面_年龄='com.kk.coachpad:id/tv_user_age'
设置页面_电话='com.kk.coachpad:id/tv_user_phone'
设置页面_版本号='com.kk.coachpad:id/tv_versionName'
设置页面_版本说明='com.kk.coachpad:id/update_content'
设置页面_关闭='com.kk.coachpad:id/btn_confirm'
首次配对='com.kk.coachpad:id/tv_start_pair'

同步电视='com.kk.coachpad:id/tv_sync_tv'
膝带左='com.kk.coachpad:id/tv_knee_strap_right'


称重按钮='com.kk.coachpad:id/tv_weight'
称重_年龄='com.kk.coachpad:id/et_age'
称重_性别男='com.kk.coachpad:id/rb_male'
称重_性别女='com.kk.coachpad:id/rb_female'
称重_安静心率='com.kk.coachpad:id/et_pluse'
称重_姓名='com.kk.coachpad:id/et_name'
称重_身高='com.kk.coachpad:id/et_height'
称重_体重='com.kk.coachpad:id/tv_weight_value'

称重_保存='com.kk.coachpad:id/tv_confirm'
称重_开始称重='com.kk.coachpad:id/tv_start_scale'
称重_首次配对='com.kk.coachpad:id/tv_start_pair'